import recipe01 from './recipe-01.json';

const ActionTypes = {
  RECIPES_LOAD_SUCCESS: 'RECIPES_LOAD_SUCCESS',

  RECIPES_SET_TEMPLATE_VARIABLE: 'RECIPES_SET_TEMPLATE_VARIABLE',

  RECIPES_CREATE_CONFIGURATIONS_START: 'RECIPES_CREATE_CONFIGURATIONS_START',
  RECIPES_CREATE_CONFIGURATIONS_SUCCESS: 'RECIPES_CREATE_CONFIGURATIONS_SUCCESS',

  RECIPES_CREATE_CONFIGURATION_START: 'RECIPES_CREATE_CONFIGURATION_START',
  RECIPES_CREATE_CONFIGURATION_SUCCESS: 'RECIPES_CREATE_CONFIGURATION_SUCCESS',
  RECIPES_CREATE_CONFIGURATION_ERROR: 'RECIPES_CREATE_CONFIGURATION_ERROR'
};

const Recipes = [
  recipe01
];

export {
  ActionTypes,
  Recipes
};
